'
' Created by SharpDevelop.
' User: Couitchy
' Date: 27/07/2009
' Time: 15:21
' 
' To change this template use Tools | Options | Coding | Edit Standard Headers.
'
Partial Class frmGrapher
	Inherits System.Windows.Forms.Form
	
	''' <summary>
	''' Designer variable used to keep track of non-visual components.
	''' </summary>
	Private components As System.ComponentModel.IContainer
	
	''' <summary>
	''' Disposes resources used by the form.
	''' </summary>
	''' <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
	Protected Overrides Sub Dispose(ByVal disposing As Boolean)
		If disposing Then
			If components IsNot Nothing Then
				components.Dispose()
			End If
		End If
		MyBase.Dispose(disposing)
	End Sub
	
	''' <summary>
	''' This method is required for Windows Forms designer support.
	''' Do not change the method contents inside the source code editor. The Forms designer might
	''' not be able to load this method if it was changed manually.
	''' </summary>
	Private Sub InitializeComponent()
		Dim resources As System.ComponentModel.ComponentResourceManager = New System.ComponentModel.ComponentResourceManager(GetType(frmGrapher))
		Me.plotMain = New NPlot.Windows.PlotSurface2D
		Me.SuspendLayout
		'
		'plotMain
		'
		Me.plotMain.AutoScaleAutoGeneratedAxes = false
		Me.plotMain.AutoScaleTitle = false
		Me.plotMain.BackColor = System.Drawing.SystemColors.ControlLightLight
		Me.plotMain.DateTimeToolTip = false
		Me.plotMain.Dock = System.Windows.Forms.DockStyle.Fill
		Me.plotMain.Legend = Nothing
		Me.plotMain.LegendZOrder = -1
		Me.plotMain.Location = New System.Drawing.Point(0, 0)
		Me.plotMain.Name = "plotMain"
		Me.plotMain.RightMenu = Nothing
		Me.plotMain.ShowCoordinates = false
		Me.plotMain.Size = New System.Drawing.Size(417, 204)
		Me.plotMain.SmoothingMode = System.Drawing.Drawing2D.SmoothingMode.None
		Me.plotMain.TabIndex = 0
		Me.plotMain.Title = ""
		Me.plotMain.TitleFont = New System.Drawing.Font("Arial", 14!, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Pixel)
		Me.plotMain.XAxis1 = Nothing
		Me.plotMain.XAxis2 = Nothing
		Me.plotMain.YAxis1 = Nothing
		Me.plotMain.YAxis2 = Nothing
		AddHandler Me.plotMain.MouseDown, AddressOf Me.PlotMainMouseDown
		'
		'frmGrapher
		'
		Me.AutoScaleDimensions = New System.Drawing.SizeF(6!, 13!)
		Me.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font
		Me.ClientSize = New System.Drawing.Size(417, 204)
		Me.Controls.Add(Me.plotMain)
		Me.Icon = CType(resources.GetObject("$this.Icon"),System.Drawing.Icon)
		Me.Name = "frmGrapher"
		Me.Text = "Tracés graphiques"
		AddHandler FormClosing, AddressOf Me.FrmGrapherFormClosing
		Me.ResumeLayout(false)
	End Sub
	Private plotMain As NPlot.Windows.PlotSurface2D
End Class
